[package]
name = "cleopatra_cairo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy-regex = "2.3.0"
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
num-integer = "0.1.45"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.1"
serde_json = "1.0"
hex = "0.4.3" 
bincode = "1.2.1"
starknet-crypto = "0.1.0"
clap = { version = "3.2.5", features = ["derive"] }

[dev-dependencies.rusty-hook]
version = "0.11"

[dev-dependencies.criterion]
version = "0.3"
features = ["html_reports"]

[[bench]]
path = "bench/criterion/criterion_benchmark.rs"
name = "criterion_benchmark"
harness = false

[[bin]]
name = "cleopatra-run"
path = "src/main.rs"
bench = false
doc = false
