name: benchmark 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Build
      run: make build
    - name: Run benchmark
      run: cargo +nightly bench --bench criterion_benchmark -- --output-format bencher |sed 1d | tee output.txt
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'cargo'
        output-file-path: output.txt
        benchmark-data-dir-path: "."
        # Access token to deploy GitHub Pages branch
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Push and deploy GitHub pages branch automatically
        auto-push: true
        alert-threshold: '130%'
        comment-on-alert: true
        alert-comment-cc-users: '@unbalancedparentheses'
    - name: Clean benches
      run: make clean
